# -*- coding: utf-8 -*-
"""niveis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MjkOxZw1VJBUsElk3TSvuUfw_v0I-PER
"""

print("Bem-vindo ao jogo de Adivinhação!")

jogarnova = "S"

while jogarnova == "S":

    numero_secreto = random.randint(1, 500)
    tentativas = 0
    print("Qual o nível de dificuldade?")
    print("(1) Fácil (2) Médio (3) Difícil")
    nivel = int(input("Defina o nível: "))
      if (nivel == 1):
total_de_tentativas = 20
    elif (nivel == 2):
total_de_tentativas = 10
else:
total_de_tentativas = 5

    while tentativas < max_tentativas:
        palpite = int(input("Digite um número entre 1 e 500: "))
        tentativas += 1

        if palpite == numero_secreto:
            print("Parabéns! Você acertou!")
            break
        elif palpite < numero_secreto:
            print("O número secreto é maior.")
        else:
            print("O número secreto é menor.")

    if tentativas == max_tentativas and palpite != numero_secreto:
        print(f"Você esgotou suas tentativas. O número secreto era {numero_secreto}.")

    jogarnova = input("Você gostaria de jogar novamente? (S/N): ").upper()

print("Obrigado por jogar!")